apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: langfuse
  template:
    metadata:
      labels:
        app: langfuse
    spec:
      containers:
      - name: langfuse
        image: langfuse:latest
        ports:
        - containerPort: 80
